class DatabaseDocker:
    DB_DATA_DIR = "RTT_DATABASE_DB_DATA_DIR"
    DB_ROOT_PASSWORD = "MYSQL_ROOT_PASSWORD"


class PyscriptBaseDocker:
    LOGS_DIR = "RTT_PYSCRIPT_BASE_LOGS_DIR"
    CONFIGS_DIR = "RTT_PYSCRIPT_BASE_CNF_DIR"


class CacheCleanerDocker:
    EXPERIMENT_FILES_DIR = "RTT_CACHE_CLEANER_EXPERIMENT_FILES_DIR"


class StorageServerDocker:
    DATA_DIR = "RTT_STORAGE_SERVER_DATA_DIR"
